/**
 * URL for the technical changelog RSS feed.
 * Generated by the new docs service at:
 * https://github.com/sourcegraph/sourcegraph/blob/main/cmd/docs/src/routes/changelog/technical-changelog.rss/%2Bserver.ts
 */
export const TECHNICAL_CHANGELOG_RSS_URL =
	'https://sourcegraph.com/changelog/technical-changelog.rss';
